apiVersion: slapper.appslap.io/v1alpha1
kind: Stdlib
metadata:
  name: stdlib
  version: 0.0.0
steps:
  - kind: provisioning
    function:
      name: xpkg.upbound.io/crossplane-contrib/function-kcl
      versionConstraint: ">=v0.10.0"
    inputFile: templates/provisioning.yaml
  - kind: backup
    function:
      name: xpkg.upbound.io/crossplane-contrib/function-kcl
      versionConstraint: ">=v0.10.0"
    inputFile: templates/backup.yaml
  - kind: monitoring
    function:
      name: xpkg.upbound.io/crossplane-contrib/function-kcl
      versionConstraint: ">=v0.10.0"
    inputFile: templates/monitoring.yaml
  - kind: maintenance
    function:
      name: xpkg.upbound.io/crossplane-contrib/function-kcl
      versionConstraint: ">=v0.10.0"
    inputFile: templates/maintenance.yaml
  - kind: networking
    function:
      name: xpkg.crossplane.io/crossplane-contrib/function-sequencer
      versionConstraint: ">=v0.5.0"
    inputFile: templates/networking.yaml
schemaFragments:
  size: schemas/size.yaml
  monitoring: schemas/monitoring.yaml
